### ISSUE TITLE
The scripts are BSD too right?

### ISSUE THREAD

**Issue by natasria** [linusg/serenityos-emoji-font#7]
Hello!

Umm all the scripts and patches are BSD too right? The license kinda says so, but it's formatted in a ambiguous manner. It feels like the scripts are All right reserved but the original emojis are all right reserved, but licensed with BSD. 

Maybe we can make the license clearer? "Both the scripts and the original emoji files are licensed under the BSD" would make it clearer for others.

**Comment by linusg** [comment]
Yep, it's all 2-Clause BSD. Thanks for the suggestion, I've added a clarification to the `LICENSE` file :)
