### ISSUE TITLE
Doesn't show up on Character Map...

### ISSUE THREAD

**Issue by NikSavchenk0** [linusg/serenityos-emoji-font#8]
![image](https://github.com/linusg/serenityos-emoji-font/assets/58150480/61df9d7b-d2bb-4182-83b1-9f5dd7dd774b)

**Comment by linusg** [comment]
They probably don't support the glyph format, that's an issue for upstream

**Comment by NikSavchenk0** [comment]
Hopefully will work smoothly with all apps soon.
