### ISSUE TITLE
Font not working as text (Windows 10)

### ISSUE THREAD

**Issue by Developer2K** [linusg/serenityos-emoji-font#9]
I downloaded nightly build from the front github page, and then installed 'SerenityOS-Emoji.ttf'. However the font does not function for me in software such as Inkscape and Paint.NET. When typing out emojis in text, they are completely invisible. Other fonts work fine and show the default Windows emojis.

**Comment by Developer2K** [comment]
Also is there a collection of .SVGs for the SerenityOS Emojis? I would love to download

**Comment by linusg** [comment]
https://superuser.com/questions/1629439/why-do-almost-none-of-my-windows-desktop-apps-display-color-emoji

> Also is there a collection of .SVGs for the SerenityOS Emojis? I would love to download

https://github.com/linusg/serenityos-emoji-font/blob/691d400ea0179b9c55157fe112f501fa61f48a0d/main.py#L55-L75
